// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example for Android:
/// Replace these values with your actual Firebase project configuration.
/// You can get these from your Firebase console > Project Settings > General tab
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlJht1Zs4rqticFvkd3PrPz5oIggQtSFg',
    appId: '1:610422771231:web:7a1eab40aeacbde39dcf2a', // Using your Android app ID for now
    messagingSenderId: '610422771231',
    projectId: 'igplrealestatecrm',
    authDomain: 'igplrealestatecrm.firebaseapp.com',
    storageBucket: 'igplrealestatecrm.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX', // You can add this later
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlJht1Zs4rqticFvkd3PrPz5oIggQtSFg',
    appId: '1:610422771231:android:7a1eab40aeacbde39dcf2a',
    messagingSenderId: '610422771231',
    projectId: 'igplrealestatecrm',
    storageBucket: 'igplrealestatecrm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlJht1Zs4rqticFvkd3PrPz5oIggQtSFg',
    appId: '1:610422771231:ios:your-ios-app-id', // You'll need to add iOS app in Firebase Console
    messagingSenderId: '610422771231',
    projectId: 'igplrealestatecrm',
    storageBucket: 'igplrealestatecrm.firebasestorage.app',
    iosBundleId: 'com.company.igpl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlJht1Zs4rqticFvkd3PrPz5oIggQtSFg',
    appId: '1:610422771231:ios:your-ios-app-id', // Same as iOS or create separate macOS app
    messagingSenderId: '610422771231',
    projectId: 'igplrealestatecrm',
    storageBucket: 'igplrealestatecrm.firebasestorage.app',
    iosBundleId: 'com.company.igpl',
  );
}